version: '3.4'

services:

  seq:
    image: datalust/seq:latest

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest 

  nosqldata:
    image: mongo

  basketdata:
    image: redis:alpine

  rabbitmq:
    image: rabbitmq:3-management-alpine

  identity-api:
    image: ${REGISTRY:-eshop}/identity.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
    depends_on:
      - sqldata
    env_file: 
      - ./../newrelic_env.list
      - ./../newrelic_license.list
    environment:
      - NEW_RELIC_APP_NAME=Identity.API

  basket-api:
    image: ${REGISTRY:-eshop}/basket.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    depends_on:
      - basketdata
      - identity-api
      - rabbitmq
    env_file: 
      - ./../newrelic_env.list
      - ./../newrelic_license.list
    environment:
      - NEW_RELIC_APP_NAME=Basket.API

  catalog-api:
    image: ${REGISTRY:-eshop}/catalog.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - sqldata
      - rabbitmq
    env_file: 
      - ./../newrelic_env.list
      - ./../newrelic_license.list
    environment:
      - NEW_RELIC_APP_NAME=Catalog.API

  ordering-api:
    image: ${REGISTRY:-eshop}/ordering.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
    depends_on:
      - sqldata
      - rabbitmq
    env_file: 
      - ./../newrelic_env.list
      - ./../newrelic_license.list
    environment:
      - NEW_RELIC_APP_NAME=Ordering.API

  ordering-backgroundtasks:
    image: ${REGISTRY:-eshop}/ordering.backgroundtasks:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.BackgroundTasks/Dockerfile
    depends_on:
      - sqldata
      - rabbitmq
    env_file: 
      - ./../newrelic_env.list
      - ./../newrelic_license.list
    environment:
      - NEW_RELIC_APP_NAME=Ordering.BackgroundTasks

  payment-api:
    image: ${REGISTRY:-eshop}/payment.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Payment/Payment.API/Dockerfile
    depends_on:
      - rabbitmq
    env_file: 
      - ./../newrelic_env.list
      - ./../newrelic_license.list
    environment:
      - NEW_RELIC_APP_NAME=Payment.API

  webhooks-api:
    image: ${REGISTRY:-eshop}/webhooks.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Webhooks/Webhooks.API/Dockerfile
    depends_on:
      - sqldata
    env_file: 
      - ./../newrelic_env.list
      - ./../newrelic_license.list
    environment:
      - NEW_RELIC_APP_NAME=Webhooks.API

  mobileshoppingapigw:
    image: envoyproxy/envoy:v1.11.1

  mobileshoppingagg:
    image: ${REGISTRY:-eshop}/mobileshoppingagg:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: ApiGateways/Mobile.Bff.Shopping/aggregator/Dockerfile
    depends_on:
      - nosqldata
      - sqldata
      - identity-api
      - rabbitmq
      - ordering-api
      - catalog-api
      - basket-api
    env_file: 
      - ./../newrelic_env.list
      - ./../newrelic_license.list
    environment:
      - NEW_RELIC_APP_NAME=Mobile.Bff.Shopping

  webshoppingagg:
    image: ${REGISTRY:-eshop}/webshoppingagg:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: ApiGateways/Web.Bff.Shopping/aggregator/Dockerfile
    depends_on:
      - nosqldata
      - sqldata
      - identity-api
      - rabbitmq
      - ordering-api
      - catalog-api
      - basket-api
    env_file: 
      - ./../newrelic_env.list
      - ./../newrelic_license.list
    environment:
      - NEW_RELIC_APP_NAME=Web.Bff.Shopping

  ordering-signalrhub:
    image: ${REGISTRY:-eshop}/ordering.signalrhub:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.SignalrHub/Dockerfile
    depends_on:
      - nosqldata
      - sqldata
      - identity-api
      - rabbitmq
      - ordering-api
      - catalog-api
      - basket-api
    env_file: 
      - ./../newrelic_env.list
      - ./../newrelic_license.list
    environment:
      - NEW_RELIC_APP_NAME=Ordering.SignalrHub

  webstatus:
    image: ${REGISTRY:-eshop}/webstatus:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Web/WebStatus/Dockerfile
    env_file: 
      - ./../newrelic_env.list
      - ./../newrelic_license.list
    environment:
      - NEW_RELIC_APP_NAME=WebStatus

  webspa:
    image: ${REGISTRY:-eshop}/webspa:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Web/WebSPA/Dockerfile
      args:
        NODE_IMAGE: ${NODE_IMAGE:-node:12.0}
    depends_on:
      - webshoppingagg
      - webshoppingapigw
    env_file: 
      - ./../newrelic_env.list
      - ./../newrelic_license.list
    environment:
      - NEW_RELIC_APP_NAME=WebSPA

  webmvc:
    image: ${REGISTRY:-eshop}/webmvc:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Web/WebMVC/Dockerfile
    depends_on:
      - webshoppingagg
      - webshoppingapigw
    env_file: 
      - ./../newrelic_env.list
      - ./../newrelic_license.list
    environment:
      - NEW_RELIC_APP_NAME=WebMVC

  webhooks-client:
    image: ${REGISTRY:-eshop}/webhooks.client:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Web/WebhookClient/Dockerfile
    depends_on:
      - webhooks-api
    env_file: 
      - ./../newrelic_env.list
      - ./../newrelic_license.list
    environment:
      - NEW_RELIC_APP_NAME=Webhooks.Client

  webshoppingapigw:
    image: envoyproxy/envoy:v1.11.1
